import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;

class PdfService {
  Future<void> generateAndShareReport({
    required String title,
    required String imageUrl,
    required Map<String, dynamic> metadata,
    required String summary,
  }) async {
    final pdf = pw.Document();

    // 1. Fetch the original image
    Uint8List? imageBytes;
    try {
      final response = await http.get(Uri.parse(imageUrl));
      if (response.statusCode == 200) {
        imageBytes = response.bodyBytes;
      }
    } catch (e) {
      // Handle image fetch failure
    }

    // --- Page 1: Original Photo ---
    if (imageBytes != null) {
      final image = pw.MemoryImage(imageBytes);
      pdf.addPage(
        pw.Page(
          build: (pw.Context context) {
            return pw.Center(
              child: pw.Image(image, fit: pw.BoxFit.contain),
            );
          },
        ),
      );
    }

    // --- Page 2: AI Summary ---
    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(30),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Zdorovya Medical Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text('Classification: ${metadata['type'] ?? 'General'}', style: pw.TextStyle(fontSize: 18, color: PdfColors.blue900)),
                pw.SizedBox(height: 10),
                pw.Text('Date: ${metadata['date'] ?? 'N/A'}'),
                pw.Text('Patient: ${metadata['patient_name'] ?? 'N/A'}'),
                pw.Text('Doctor/Facility: ${metadata['doctor_name'] ?? 'N/A'}'),
                pw.SizedBox(height: 30),
                pw.Text('AI Summary:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.Text(summary),
                pw.SizedBox(height: 30),
                if (metadata['medicines'] != null && (metadata['medicines'] as List).isNotEmpty) ...[
                  pw.Text('Detected Medications:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 10),
                  ...(metadata['medicines'] as List).map((m) => pw.Bullet(text: '${m['name']} (${m['dosage'] ?? 'No dosage'})')),
                ],
                pw.Spacer(),
                pw.Divider(),
                pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text('Generated by Zdorovya App', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                ),
              ],
            ),
          );
        },
      ),
    );

    // 2. Share/Download
    await Printing.sharePdf(bytes: await pdf.save(), filename: 'report_${DateTime.now().millisecondsSinceEpoch}.pdf');
  }
}

final pdfService = PdfService();
